const $ = id => document.getElementById(id);
const state = { market:'us', rank:50, filter:'all', current:null, search:null, rows:[], watch:readWatch() };
const escapeHtml = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = (v, digits=2) => v == null ? '—' : Number(v).toLocaleString('ko-KR',{maximumFractionDigits:digits});
const percent = v => v == null ? '—' : `${v>0?'+':''}${number(v)}%`;
function readWatch(){try{return JSON.parse(localStorage.getItem('hongpick.watch.v1')||'[]').filter(x=>x && x.tv && x.symbol).slice(0,100)}catch{return []}}
function saveWatch(){localStorage.setItem('hongpick.watch.v1',JSON.stringify(state.watch));renderWatch()}
async function api(path){const r=await fetch(path);const data=await r.json();if(!r.ok)throw Error(data.error||'데이터 없음');return data}
function show(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));window.scrollTo(0,0);if(id==='watchlist')renderWatch();if(id==='turnover')loadTurnover()}
function chart(target,item){target.replaceChildren();if(!item?.tv){target.textContent='확인된 거래소 심볼이 없습니다.';return}if(item.tv.startsWith('KRX:')){const note=document.createElement('div');note.className='chart-unavailable';note.innerHTML='<b>한국 종목 차트</b><p>TradingView 무료 임베드에서 이 거래소 심볼을 표시할 수 없습니다. 전체 TradingView 화면에서 확인해 주세요.</p>';const link=document.createElement('a');link.href='https://www.tradingview.com/chart/?symbol='+encodeURIComponent(item.tv);link.target='_blank';link.rel='noopener noreferrer';link.textContent='TradingView에서 차트 열기 ↗';note.append(link);target.append(note);return}const wrap=document.createElement('div');wrap.style.cssText='width:100%;height:100%;min-width:0';const script=document.createElement('script');script.src='https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js';script.async=true;script.text=JSON.stringify({autosize:true,symbol:item.tv,interval:'D',timezone:'Asia/Seoul',theme:'dark',style:'1',locale:'kr',allow_symbol_change:false,hide_side_toolbar:true,hide_top_toolbar:true,hide_legend:false,hide_volume:false,save_image:false,calendar:false,details:false,hotlist:false,withdateranges:true,backgroundColor:'#0b1927',gridColor:'rgba(130,160,180,.08)'});wrap.append(script);target.append(wrap)}
function renderChart(item, mode){if(mode==='search'){state.search=item;$('searchTitle').textContent=item.name||item.symbol;$('searchSub').textContent=item.tv;chart($('searchChart'),item);updateWatchButton('searchIndicators',item)}else{state.current=item;$('chartTitle').textContent=item.name||item.symbol;$('turnChartSub').textContent=item.tv;chart($('chart'),item);updateWatchButton('turnIndicators',item)}}
function updateWatchButton(id,item){const saved=state.watch.some(x=>x.tv===item.tv);$(id).innerHTML=`<button class="watch-add" data-watch="${escapeHtml(item.tv)}">${saved?'★ 관심종목 해제':'☆ 관심종목 저장'}</button><div class="indicator-buttons"><button disabled title="무료 임베드에서 서로 다른 MA 입력을 정확하게 지정할 수 없습니다">MA 20/60/120/200</button><button disabled title="무료 임베드의 지표 상태를 외부 버튼과 동기화할 수 없습니다">RSI(14)</button><button disabled title="무료 임베드에서 일목균형표 세부 입력과 구름 투명도를 검증할 수 없습니다">일목균형표</button></div><small class="indicator-note">무료 TradingView 임베드는 지정 기간의 복수 MA와 일목 설정을 정확하게 제어할 수 없어 버튼을 비활성화했습니다. 차트의 TradingView 지표 메뉴에서 직접 추가할 수 있습니다.</small>`}
async function search(){const q=$('searchInput').value.trim();if(!q)return;const out=$('searchResults');out.textContent='검색 중…';try{const d=await api('/api/search?q='+encodeURIComponent(q));out.replaceChildren();if(!d.results.length){out.textContent='검색 결과가 없습니다. 데이터 제공자 연결 상태를 확인해 주세요.';return}for(const item of d.results){const b=document.createElement('button');b.innerHTML=`${escapeHtml(item.name)} <small>${escapeHtml(item.symbol)} · ${escapeHtml(item.tv)}</small>`;b.onclick=()=>{renderChart(item,'search');out.replaceChildren();$('searchInput').value=item.name;loadDetails(item)};out.append(b)}}catch(e){out.textContent=e.message}}
async function loadDetails(item){try{const d=await api('/api/stock?symbol='+encodeURIComponent(item.symbol));$('searchSub').textContent=`${item.tv} · ${number(d.price)} · RSI ${number(d.rsi,1)} · 52주 고점 대비 ${percent(d.drawdown)} · ${d.source} · ${d.updated||'시각 없음'}`}catch{$('searchSub').textContent=item.tv+' · 가격 데이터 없음'}}
async function loadTurnover(){const status=$('turnStatus');$('turnTitle').textContent=(state.market==='kr'?'한국':'미국')+' 거래대금 TOP 50';status.textContent='불러오는 중…';try{const d=await api('/api/turnover?market='+state.market);state.rows=d.rows||[];status.textContent=d.error||`${d.source} · ${d.updated||'갱신 시각 없음'}`;renderRows()}catch(e){state.rows=[];status.textContent=e.message;renderRows()}}
function renderRows(){let rows=state.rows.slice(0,state.rank);const f=state.filter;rows=rows.filter(x=>f==='all'||(f==='rsi30'&&x.rsi!=null&&x.rsi<=30)||(f==='rsi25'&&x.rsi!=null&&x.rsi>=25&&x.rsi<=35)||(f==='rsi40'&&x.rsi!=null&&x.rsi<=40)||(f==='dd30'&&x.drawdown!=null&&x.drawdown<=-30)||(f==='dd50'&&x.drawdown!=null&&x.drawdown<=-50)||(f==='surge'&&x.surge===true));$('rows').innerHTML=rows.length?rows.map((x,i)=>`<tr data-index="${i}"><td>${x.rank||i+1}</td><td>${escapeHtml(x.name)}<br><small>${escapeHtml(x.symbol)}</small></td><td>${number(x.price)}</td><td>${percent(x.change)}</td><td>${number(x.turnover,0)}</td><td>${number(x.rsi,1)}</td><td>${percent(x.drawdown)}</td></tr>`).join(''):'<tr><td colspan="7" class="empty">검증된 거래대금 순위 데이터가 없습니다. 임의 순위를 표시하지 않습니다.</td></tr>';document.querySelectorAll('#rows tr[data-index]').forEach(row=>row.onclick=()=>{const x=rows[Number(row.dataset.index)];if(x?.tv)renderChart(x,'turn')})}
async function loadFng(){try{const d=await api('/api/fng');const v=Math.max(0,Math.min(100,Number(d.value)));$('fngValue').textContent=$('homeFng').textContent=$('homeGaugeValue').textContent=v;$('fngLabel').textContent=$('homeFngLabel').textContent=d.classification;$('homeGaugeMarker').style.left=v+'%';$('homeGaugeMarker').style.display='block';$('fngDescription').textContent=d.classification;$('status').textContent='● 실제 데이터 · 암호화폐 심리';$('fngSource').textContent=`${d.source} · ${d.updated} UTC`;const hist=$('fngHistory');hist.innerHTML=d.history.map(x=>`<span class="${x.value<40?'low':''}" style="height:${x.value}%" title="${escapeHtml(x.date)}: ${x.value}"></span>`).join('')}catch(e){$('status').textContent='● 데이터 없음';$('fngSource').textContent=e.message;$('homeGaugeMarker').style.display='none'}}
async function loadDisclosures(){for(const [path,id] of [['gurus','guruCards'],['trump','trumpData']]){try{const d=await api('/api/'+path);$(id).textContent=d.error||'데이터 없음'}catch(e){$(id).textContent=e.message}}$('consensus').textContent='공시 기반 복수 투자자 매수 신호 데이터 없음';$('homeStocks').textContent='공시 기반 매수 신호 데이터 없음'}
async function renderWatch(){const root=$('watch');root.replaceChildren();if(!state.watch.length){root.textContent='저장된 관심종목이 없습니다. 검색에서 종목을 선택해 저장해 주세요.';return}for(const item of state.watch){const div=document.createElement('div');div.className='stock';div.innerHTML=`<div><b>${escapeHtml(item.name||item.symbol)}</b><span>${escapeHtml(item.tv)}</span></div><div class="right">가격 불러오는 중</div><button data-remove="${escapeHtml(item.tv)}" aria-label="관심종목 삭제">×</button>`;div.querySelector('div').onclick=()=>{renderChart(item,'search');show('search')};root.append(div);try{const d=await api('/api/stock?symbol='+encodeURIComponent(item.symbol));div.querySelector('.right').innerHTML=`${number(d.price)} · ${percent(d.change)}<br><small>RSI ${number(d.rsi,1)} · 고점 ${percent(d.drawdown)}<br>순위/13F 데이터 없음</small>`}catch{div.querySelector('.right').textContent='가격 데이터 없음'}}}
document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go)show(go.dataset.go);const market=e.target.closest('[data-market]');if(market){document.querySelectorAll('[data-market]').forEach(x=>x.classList.toggle('sel',x===market));state.market=market.dataset.market;loadTurnover()}const filter=e.target.closest('[data-filter]');if(filter){document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('sel',x===filter));state.filter=filter.dataset.filter;renderRows()}const rank=e.target.closest('[data-rank]');if(rank){document.querySelectorAll('[data-rank]').forEach(x=>x.classList.toggle('sel',x===rank));state.rank=Number(rank.dataset.rank);renderRows()}for(const [attr,id,key] of [['data-size','chart','current'],['data-search-size','searchChart','search']]){const size=e.target.closest('['+attr+']');if(size){size.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('sel',x===size));$(id).className='chart '+size.getAttribute(attr);if(state[key])chart($(id),state[key])}}const hint=e.target.closest('[data-symbol]');if(hint){$('searchInput').value=hint.dataset.name||hint.dataset.symbol;show('search');search()}const add=e.target.closest('[data-watch]');if(add){const item=[state.search,state.current].find(x=>x?.tv===add.dataset.watch);if(item){state.watch=state.watch.some(x=>x.tv===item.tv)?state.watch.filter(x=>x.tv!==item.tv):[...state.watch,item];saveWatch();updateWatchButton(add.closest('.indicator-area').id,item)}}const remove=e.target.closest('[data-remove]');if(remove){state.watch=state.watch.filter(x=>x.tv!==remove.dataset.remove);saveWatch()}});
$('searchBtn').onclick=search;$('searchInput').onkeydown=e=>{if(e.key==='Enter')search()};$('refresh').onclick=()=>{loadFng();loadTurnover()};renderChart({symbol:'NVDA',name:'NVIDIA',tv:'NASDAQ:NVDA'},'search');renderChart({symbol:'NVDA',name:'NVIDIA',tv:'NASDAQ:NVDA'},'turn');loadFng();loadDisclosures();loadTurnover();setInterval(loadFng,60*60*1000);setInterval(()=>{if($('turnover').classList.contains('active'))loadTurnover()},5*60*1000);
