const $=id=>document.getElementById(id);
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=(v,digits=2)=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('ko-KR',{maximumFractionDigits:digits});
const percent=v=>v==null?'—':`${v>0?'+':''}${number(v)}%`;
const formatDate=v=>{if(!v)return'시각 없음';const d=new Date(v);return isNaN(d)?v:d.toLocaleString('ko-KR',{timeZone:'Asia/Seoul',hour12:false})+' KST'};
function readWatch(){try{return JSON.parse(localStorage.getItem('hongpick.watch.v1')||'[]').filter(x=>x?.tv).slice(0,100)}catch{return[]}}
function readFngKind(){try{return localStorage.getItem('hongpick.fng.kind')==='crypto'?'crypto':'stock'}catch{return 'stock'}}
const state={market:'us',rank:50,filters:new Set(),rows:[],watch:readWatch(),search:null,current:null,gurus:null,guruIndex:0,guruFilter:'all',trump:null,trumpFilter:'all',trumpQuery:'',fngKind:readFngKind(),loaded:new Set(),page:'home'};
const charts={};
let picksPending=null,picksData=null,picksMarket='all';
async function api(path){
 return HongData.api(path);
}
let chartScripts;
function ensureCharts(){if(!chartScripts)chartScripts=(async()=>{for(const name of ['fib-client.js?v=5.6','lightweight-charts.js','charts.js?v=5.6'])await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=HongData.asset(name);script.onload=resolve;script.onerror=()=>{script.remove();reject(Error('차트 모듈을 불러오지 못했습니다.'))};document.head.append(script)})})().catch(error=>{chartScripts=null;throw error});return chartScripts}
function notice(root,text){root.innerHTML='<div class="empty">'+escapeHtml(text)+'</div>'}
function source(d){return `${d.source||''} · 기준시각 ${formatDate(d.updated)}${d.stale?' · 이전 데이터':''}`}
const pages=['hongpicks','home','search','gurus','turnover','fng','trump','watchlist'];
function show(id,updateHash=true){
 if(!pages.includes(id))id='home';state.page=id;
 document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));
 document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.go===id);b.setAttribute('aria-current',b.dataset.go===id?'page':'false')});
 window.scrollTo(0,0);if(updateHash&&location.hash!=='#'+id)location.hash=id;
 if(id==='watchlist')renderWatch();if(id==='turnover')loadTurnover();if(id==='gurus')loadGurus();if(id==='trump'&&!state.trump)loadTrump();if(id==='fng')loadFng();
 if(id==='home'){loadOverview();loadFng();loadGurus();loadPicks()}if(id==='hongpicks')loadPicks();
 if(id==='search'&&!charts.search)renderChart(state.search||{tv:'NASDAQ:NVDA',symbol:'NASDAQ:NVDA',name:'NVIDIA',ticker:'NVDA'},'search');
 requestAnimationFrame(()=>Object.values(charts).forEach(x=>x.resize()));
}
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1)||'home';if(id!==state.page)show(id,false)});
async function renderChart(item,mode='search'){if(!item?.tv)return;const searchMode=mode==='search',key=searchMode?'search':'current';state[key]=item;$(searchMode?'searchTitle':'chartTitle').textContent=item.name||item.ticker||item.symbol;$(searchMode?'searchSub':'turnChartSub').textContent=item.tv;const target=$(searchMode?'searchChart':'chart'),controls=$(searchMode?'searchIndicators':'turnIndicators');if(searchMode)loadDetails(item);try{await ensureCharts();if(state[key]?.tv!==item.tv)return;if(!charts[mode])charts[mode]=new HongChart(target,controls);charts[mode].load(item)}catch(e){notice(target,e.message)}}
function openStock(item){state.search=item;const ready=!!charts.search;show('search');if(ready)renderChart(item,'search')}
let searchToken=0;
async function search(){const q=$('searchInput').value.trim();if(!q)return;const token=++searchToken;notice($('searchResults'),'검색 중…');try{const d=await api('/api/search?q='+encodeURIComponent(q));if(token!==searchToken)return;const root=$('searchResults');root.replaceChildren();if(!d.results.length){notice(root,d.error||'검색 결과가 없습니다. 종목명 또는 티커를 확인해 주세요.');return}for(const item of d.results){const b=document.createElement('button');b.innerHTML=`${escapeHtml(item.name)}<small>${escapeHtml(item.ticker)} · ${escapeHtml(item.tv)} · ${item.type==='fund'?'ETF':'주식'}</small>`;b.onclick=()=>{renderChart(item,'search');root.replaceChildren();$('searchInput').value=item.name};root.append(b)}}catch(e){if(token===searchToken)notice($('searchResults'),e.message)}}
async function loadDetails(item){try{const d=await api('/api/stock?symbol='+encodeURIComponent(item.tv));if(state.search?.tv!==item.tv)return;$('searchSub').textContent=`${item.tv} · ${number(d.price)} ${d.currency} · ${percent(d.change)} · RSI ${number(d.rsi,1)} · 고점 ${percent(d.drawdown)} · 지연 시세`;$('searchQuoteSource').textContent=source(d)}catch(e){if(state.search?.tv===item.tv)$('searchQuoteSource').textContent=e.message}}
let turnoverToken=0;
async function loadTurnover(){const token=++turnoverToken,market=state.market;if(state.rowMarket!==market){state.rows=[];$('rows').innerHTML='<tr><td colspan="7" class="empty">선택한 시장을 불러오는 중…</td></tr>'}$('turnTitle').textContent=(market==='kr'?'한국':'미국')+' 거래대금 TOP '+state.rank+' · 추정';$('turnStatus').textContent='불러오는 중…';try{const d=await api('/api/turnover?market='+market);if(token!==turnoverToken)return;state.rows=d.rows;state.rowMarket=market;$('turnStatus').textContent=source(d);$('turnMethod').textContent=d.coverage+' · '+d.method+(d.notice?' · '+d.notice:'');renderRows();if(!state.current||(state.current.tv.startsWith('KRX:')?'kr':'us')!==market)renderChart(d.rows[0],'turn')}catch(e){if(token!==turnoverToken)return;state.rows=[];$('turnStatus').textContent=e.message;renderRows()}}
function renderRows(){let rows=state.rows.slice(0,state.rank);const tests={rsi30:x=>x.rsi!=null&&x.rsi<=30,rsi25:x=>x.rsi!=null&&x.rsi>=25&&x.rsi<=35,rsi40:x=>x.rsi!=null&&x.rsi<=40,dd30:x=>x.drawdown!=null&&x.drawdown<=-30,dd50:x=>x.drawdown!=null&&x.drawdown<=-50,surge:x=>x.surge===true};rows=rows.filter(x=>[...state.filters].every(f=>tests[f](x)));$('turnTitle').textContent=(state.market==='kr'?'한국':'미국')+' 거래대금 TOP '+state.rank+' · 추정';$('filterCount').textContent=`${rows.length}개 결과 · 선택한 조건 모두 충족`;const root=$('rows');root.innerHTML=rows.length?rows.map((x,i)=>`<tr tabindex="0" data-index="${i}"><td>${x.rank}</td><td>${escapeHtml(x.name)}<br><small>${escapeHtml(x.tv)}</small></td><td>${number(x.price)}<small> ${x.currency}</small></td><td class="${x.change<0?'down':'up'}">${percent(x.change)}</td><td>${compactMoney(x.turnover,x.currency)}</td><td>${number(x.rsi,1)}</td><td>${percent(x.drawdown)}</td></tr>`).join(''):'<tr><td colspan="7" class="empty">'+(state.rows.length?'조건을 충족하는 종목이 없습니다. 필터를 조정해 주세요.':'거래대금 데이터 없음')+'</td></tr>';root.querySelectorAll('[data-index]').forEach(row=>{const action=()=>{renderChart(rows[+row.dataset.index],'turn');$('chart').scrollIntoView({behavior:'smooth',block:'center'})};row.onclick=action;row.onkeydown=e=>{if(e.key==='Enter')action()}})}
function compactMoney(v,c){if(v==null)return'—';if(c==='KRW')return number(v/1e8,1)+'억';return'$'+number(v/1e6,1)+'M'}
async function loadOverview(){
 const cards=document.querySelectorAll('.markets article');
 try{const d=await api('/api/overview');d.rows.forEach((x,i)=>{cards[i].querySelector('b').textContent=x.price==null?'데이터 없음':number(x.price);cards[i].querySelector('em').textContent=percent(x.change);cards[i].querySelector('em').classList.toggle('down',x.change<0);cards[i].title=source(x)});$('overviewSource').textContent=d.rows.map(x=>x.name+' · '+(x.price==null?'데이터 없음':formatDate(x.updated)+(x.stale?' · 이전 데이터':''))).join(' / ')+' · Yahoo Finance'}
 catch(e){cards.forEach((x,i)=>{if(i<3){x.querySelector('b').textContent='데이터 없음';x.querySelector('em').textContent='—'}});$('overviewSource').textContent=e.message}
}
function sentimentLabels(kind){
 const stock=kind==='stock';$('homeFngTitle').textContent=(stock?'미국 주식':'암호화폐')+' Fear & Greed';$('fngDescription').textContent=stock?'미국 주식시장 심리':'암호화폐 시장 심리';
 document.querySelectorAll('[data-fng-kind]').forEach(b=>b.classList.toggle('sel',b.dataset.fngKind===kind));
 $('fngOfficial').href=stock?'https://www.cnn.com/markets/fear-and-greed':'https://alternative.me/crypto/fear-and-greed-index/';$('fngOfficial').textContent=(stock?'CNN':'Alternative.me')+' 공식 지표 ↗';
}
function clearFng(kind,message,loading=false){
 sentimentLabels(kind);$('fngValue').textContent=$('homeFng').textContent='—';$('fngLabel').textContent=$('homeFngLabel').textContent=loading?'불러오는 중…':'데이터 없음';$('homeGaugeValue').textContent=loading?'불러오는 중…':'데이터 없음';$('fngSource').textContent=$('homeFngSource').textContent=message;
 $('fngHistory').replaceChildren();$('fngHistoryDates').textContent='';$('fngMarker').style.display=$('homeGaugeMarker').style.display='none';
}
let fngToken=0;
async function loadFng(){
 const kind=state.fngKind,token=++fngToken;clearFng(kind,'제공원에서 시장 심리를 확인하는 중…',true);
 try{const d=await api('/api/fng?kind='+kind);if(token!==fngToken)return;const v=Number(d.value);if(!Number.isFinite(v)||v<0||v>100)throw Error('유효한 지표 데이터 없음');
 $('fngValue').textContent=$('homeFng').textContent=$('homeGaugeValue').textContent=number(v,0);$('fngLabel').textContent=$('homeFngLabel').textContent=d.classification;$('fngSource').textContent=$('homeFngSource').textContent=source(d);
 for(const id of ['fngMarker','homeGaugeMarker']){$(id).style.left=v+'%';$(id).style.display='block'}
 $('fngHistory').innerHTML=d.history.slice(-90).map(x=>`<span class="${x.value<40?'low':''}" style="height:${x.value}%" title="${escapeHtml(x.date)}: ${number(x.value,0)}"></span>`).join('');$('fngHistoryDates').textContent=d.history.length?d.history.slice(-90)[0].date+' → '+d.history.at(-1).date+' · 최근 90일':'';
 }catch(e){if(token===fngToken)clearFng(kind,e.message)}
}
const statusNames={scope_change:'범위 변경',new:'신규',increase:'추가',reduce:'감축',sold:'전량매도',unchanged:'유지'};
async function loadGurus(){notice($('guruCards'),'SEC 공시를 불러오는 중…');try{state.gurus=await api('/api/gurus');const d=state.gurus;$('guruCards').innerHTML=d.rows.map((x,i)=>`<button class="guru ${i===state.guruIndex?'sel':''}" data-guru="${i}"><b>${escapeHtml(x.name)}</b><span>${escapeHtml(x.person)}<br>${x.quarter||'데이터 없음'} · 공시 ${x.filed||'—'}</span><strong>${x.comparisonAvailable===false?'보고 범위 변경 · 비교 제외':x.counts?'신규 '+x.counts.new+' · 추가 '+x.counts.increase:escapeHtml(x.error)}</strong>${x.stale?'<small>이전 수집 데이터</small>':''}</button>`).join('');$('guruSource').textContent=d.notice+(d.mixedQuarters?' · 투자자별 보고 분기가 다릅니다.':'');renderGuru();const render=(rows,id)=>{const root=$(id);root.innerHTML=rows.map((x,i)=>`<button class="consensus-stock" data-consensus="${i}"><b>${escapeHtml(x.ticker||x.name)}</b><span>${x.held}명 보유 · ${x.increase}명 추가 · ${x.new}명 신규</span><small>${[...new Set(x.quarters)].join(' / ')}</small></button>`).join('');root.querySelectorAll('button').forEach(b=>b.onclick=()=>{const x=rows[+b.dataset.consensus];if(x.tv)openStock(x);else{$('searchInput').value=x.name;show('search');search()}})};render(d.consensus.slice(0,30),'consensus');render(d.consensus.filter(x=>x.new+x.increase>=2).slice(0,4),'homeStocks');if(!$('homeStocks').children.length)notice($('homeStocks'),'복수 투자자의 주식수 증가 신호가 없습니다.')}catch(e){notice($('guruCards'),e.message);notice($('homeStocks'),e.message)}}
function renderGuru(){const inv=state.gurus?.rows[state.guruIndex];if(!inv)return;$('guruTitle').textContent=inv.name;$('guruQuarter').innerHTML=inv.quarter?`분기말 ${inv.quarter} · 보고일 ${inv.filed} · 이전 ${inv.previousQuarter} · <a href="${escapeHtml(inv.sourceUrl)}" target="_blank" rel="noopener noreferrer">SEC 원문 ↗</a>`:escapeHtml(inv.error);if(inv.reportingNotice){$('guruQuarter').innerHTML+=`<br>보고 주체: ${escapeHtml(inv.reportingManager)} · <a href="${escapeHtml(inv.reportingNotice.sourceUrl)}" target="_blank" rel="noopener noreferrer">보고 주체 변경 공시 ↗</a>`}if(inv.filings?.some(x=>x.type!=='13F-HR')){$('guruQuarter').innerHTML+='<br>정정공시 반영: '+inv.filings.map(x=>`<a href="${escapeHtml(x.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(x.type)} (${x.filed})</a>`).join(' · ')}if(inv.comparisonNote)$('guruQuarter').innerHTML+='<br>'+escapeHtml(inv.comparisonNote);const rows=inv.holdings.filter(x=>state.guruFilter==='all'||x.status===state.guruFilter);$('guruRows').innerHTML=rows.length?rows.map((x,i)=>`<tr data-holding="${i}" tabindex="0"><td>${escapeHtml(x.name)}<br><small>${escapeHtml(x.ticker||('CUSIP '+x.cusip))} · ${escapeHtml(x.class)}</small></td><td><span class="badge ${x.status}">${statusNames[x.status]}</span></td><td>${number(x.shares,0)}</td><td>${percent(x.shareChange)}</td><td>${number(x.weight)}%</td><td>${x.previousWeight==null?'비교 없음':number(x.previousWeight)+'% → '+number(x.weight)+'%<br>'+percent(x.weightChange)+'p'}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">해당 공시 내역 없음</td></tr>';$('guruRows').querySelectorAll('[data-holding]').forEach(b=>{const action=()=>{const x=rows[+b.dataset.holding];if(x.tv)openStock(x);else{$('searchInput').value=x.name;show('search');search()}};b.onclick=action;b.onkeydown=e=>{if(e.key==='Enter')action()}})}
async function loadTrump(){notice($('trumpData'),'공식 OGE 공시를 불러오는 중…');try{state.trump=await api('/api/trump');const d=state.trump;$('trumpCoverage').textContent=d.coverage+' · '+source(d);$('trumpReports').innerHTML=d.reports.map(r=>`<a class="report" href="${escapeHtml(r.sourceUrl)}" target="_blank" rel="noopener noreferrer"><b>공개일 ${r.publicDate}</b><span>${escapeHtml(r.type)} · 공식 PDF ↗</span></a>`).join('');$('trumpCatalogSource').textContent='OGE 공식 목록 · 확인 '+formatDate(d.catalogUpdated)+(d.catalogStale?' · 이전 수집 목록':'');renderTrump()}catch(e){notice($('trumpData'),e.message)}}
function renderTrump(){const rows=state.trump.rows.filter(x=>(state.trumpFilter==='all'||x.action===state.trumpFilter)&&(!state.trumpQuery||(x.name+' '+x.ticker).toLowerCase().includes(state.trumpQuery)));$('trumpCount').textContent=`검증된 ${state.trump.rows.length}건 중 ${rows.length}건 표시`;if(!rows.length){notice($('trumpData'),'조건에 맞는 공시 내역이 없습니다.');return}$('trumpData').innerHTML='<div class="table"><table><thead><tr><th>종목</th><th>구분</th><th>거래일</th><th>공개일</th><th>신고 금액 범위</th><th>공개 이후 주가</th><th>원문</th></tr></thead><tbody>'+rows.map((x,i)=>`<tr><td><button data-trump-stock="${i}">${escapeHtml(x.name)}<small> ${x.ticker}</small></button></td><td class="${x.action==='buy'?'up':'down'}">${x.action==='buy'?'매수':'매도'}</td><td>${x.tradeDate}</td><td>${x.publicDate}</td><td>${escapeHtml(x.amount)}</td><td><button data-performance="${i}">계산</button></td><td><a href="${escapeHtml(x.sourceUrl)}#page=${x.page}" target="_blank" rel="noopener noreferrer">p.${x.page} #${x.id} ↗</a></td></tr>`).join('')+'</tbody></table></div>';$('trumpData').querySelectorAll('[data-trump-stock]').forEach(b=>b.onclick=()=>openStock(rows[+b.dataset.trumpStock]));$('trumpData').querySelectorAll('[data-performance]').forEach(b=>b.onclick=async()=>{const x=rows[+b.dataset.performance];b.disabled=true;b.textContent='계산 중';try{const d=await api('/api/disclosure-performance?symbol='+encodeURIComponent(x.tv)+'&date='+x.publicDate);b.textContent=percent(d.change);b.title=`${d.baselineDate} 종가 ${number(d.baseline)} → ${d.latestDate} 종가 ${number(d.latest)} · ${d.source} · 배당 미포함`}catch(e){b.textContent='데이터 없음';b.title=e.message}finally{b.disabled=false}})}
function saveWatch(){try{localStorage.setItem('hongpick.watch.v1',JSON.stringify(state.watch))}catch{alert('브라우저 저장 공간에 접근할 수 없습니다.')}Object.values(charts).forEach(c=>c.renderControls());if(state.page==='watchlist')renderWatch()}
let watchToken=0;
async function renderWatch(){
 const token=++watchToken,root=$('watch');root.replaceChildren();if(!state.watch.length){notice(root,'종목 검색 또는 차트 아래 ☆ 버튼으로 관심종목을 저장하세요.');return}
 const ranks={},rankReady={},entries=state.watch.map(item=>{const div=document.createElement('div');div.className='stock';div.innerHTML=`<button class="stock-name"><b>${escapeHtml(item.name||item.ticker||item.symbol)}</b><span>${escapeHtml(item.tv)}</span></button><div class="right">시세 확인 중…</div><button data-remove="${escapeHtml(item.tv)}" aria-label="관심종목 삭제">×</button>`;div.querySelector('.stock-name').onclick=()=>openStock(item);root.append(div);return{item,div,quote:null,error:null}});
 let guruReady=!!state.gurus;
 const paint=entry=>{if(token!==watchToken)return;const {item,div,quote:x,error}=entry;if(error){div.querySelector('.right').textContent=error;return}if(!x)return;const market=item.tv.startsWith('KRX:')?'kr':'us',signal=state.gurus?.consensus.find(y=>y.tv===item.tv);div.querySelector('.right').innerHTML=`${number(x.price)} ${x.currency} · <span class="${x.change<0?'down':'up'}">${percent(x.change)}</span><small>RSI ${number(x.rsi,1)} · 52주 고점 ${percent(x.drawdown)}<br>거래대금 ${ranks[item.tv]?'TOP '+ranks[item.tv]:rankReady[market]?'TOP50 밖/데이터 없음':'순위 확인 중…'}<br>${signal?signal.held+'명 보유 · 추가 '+signal.increase+' · 신규 '+signal.new:guruReady?'13F 보유 신호 없음/미확인':'13F 확인 중…'}<br>${escapeHtml(x.source)} · ${formatDate(x.updated)}${x.stale?' · 이전 데이터':''}</small>`};
 const enrichment=Promise.all([
  ...['us','kr'].filter(m=>entries.some(x=>(x.item.tv.startsWith('KRX:')?'kr':'us')===m)).map(async m=>{try{const r=await api('/api/turnover?market='+m);r.rows.forEach(x=>ranks[x.tv]=x.rank)}catch{}finally{rankReady[m]=true;entries.forEach(paint)}}),
  (async()=>{if(!state.gurus)try{state.gurus=await api('/api/gurus')}catch{}guruReady=true;entries.forEach(paint)})()
 ]);
 let cursor=0;await Promise.all(Array.from({length:Math.min(4,entries.length)},async()=>{while(cursor<entries.length){const entry=entries[cursor++];try{entry.quote=await api('/api/stock?symbol='+encodeURIComponent(entry.item.tv))}catch(e){entry.error=e.message}paint(entry)}}));await enrichment;
}
document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go)show(go.dataset.go);const market=e.target.closest('[data-market]');if(market){state.market=market.dataset.market;document.querySelectorAll('[data-market]').forEach(b=>b.classList.toggle('sel',b===market));loadTurnover()}const filter=e.target.closest('[data-filter]');if(filter){const f=filter.dataset.filter;if(f==='all')state.filters.clear();else{if(f.startsWith('rsi'))for(const v of [...state.filters])if(v.startsWith('rsi'))state.filters.delete(v);if(f.startsWith('dd'))for(const v of [...state.filters])if(v.startsWith('dd'))state.filters.delete(v);filter.classList.contains('sel')?state.filters.delete(f):state.filters.add(f)}document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('sel',b.dataset.filter==='all'?state.filters.size===0:state.filters.has(b.dataset.filter)));renderRows()}const rank=e.target.closest('[data-rank]');if(rank){state.rank=+rank.dataset.rank;document.querySelectorAll('[data-rank]').forEach(b=>b.classList.toggle('sel',b===rank));renderRows()}for(const [attr,id,key]of[['data-search-size','searchChart','search'],['data-size','chart','turn']]){const size=e.target.closest('['+attr+']');if(size){size.parentElement.querySelectorAll('button').forEach(b=>b.classList.toggle('sel',b===size));$(id).className='chart '+size.getAttribute(attr);charts[key]?.resize()}}const hint=e.target.closest('[data-symbol]');if(hint){$('searchInput').value=hint.dataset.name||hint.dataset.symbol;show('search');search()}const add=e.target.closest('[data-watch]');if(add){const item=[state.search,state.current].find(x=>x?.tv===add.dataset.watch);if(item){state.watch=state.watch.some(x=>x.tv===item.tv)?state.watch.filter(x=>x.tv!==item.tv):[...state.watch,item];saveWatch()}}const remove=e.target.closest('[data-remove]');if(remove){state.watch=state.watch.filter(x=>x.tv!==remove.dataset.remove);saveWatch()}const guru=e.target.closest('[data-guru]');if(guru){state.guruIndex=+guru.dataset.guru;document.querySelectorAll('[data-guru]').forEach(b=>b.classList.toggle('sel',b===guru));renderGuru()}const gf=e.target.closest('[data-guru-filter]');if(gf){state.guruFilter=gf.dataset.guruFilter;document.querySelectorAll('[data-guru-filter]').forEach(b=>b.classList.toggle('sel',b===gf));renderGuru()}const tf=e.target.closest('[data-trump-filter]');if(tf){state.trumpFilter=tf.dataset.trumpFilter;document.querySelectorAll('[data-trump-filter]').forEach(b=>b.classList.toggle('sel',b===tf));if(state.trump)renderTrump()}const kind=e.target.closest('[data-fng-kind]');if(kind){state.fngKind=kind.dataset.fngKind;try{localStorage.setItem('hongpick.fng.kind',state.fngKind)}catch{}loadFng()}});
$('trumpSearch').oninput=e=>{state.trumpQuery=e.target.value.trim().toLowerCase();if(state.trump)renderTrump()};
$('searchBtn').onclick=search;$('searchInput').onkeydown=e=>{if(e.key==='Enter')search()};$('refresh').onclick=()=>{HongData.clear();if(state.page==='hongpicks')loadPicks();else if(state.page==='turnover')loadTurnover();else if(state.page==='gurus')loadGurus();else if(state.page==='trump')loadTrump();else if(state.page==='search'&&state.search)renderChart(state.search,'search');else if(state.page==='watchlist')renderWatch();else{loadOverview();loadFng();if(state.page==='home'){loadGurus();loadPicks()}}};
$('status').textContent=HongData.staticMode?'● 주기 수집 · 실제 데이터':'● 공개 제공원 · 지연 시세';if(HongData.staticMode){$('dataMode').hidden=false;$('apiFallback').checked=HongData.fallback;$('apiFallback').onchange=e=>{HongData.setFallback(e.target.checked);$('dataModeStatus').textContent=HongData.fallback?'· API 보완 켜짐':'· Render 요청 없음'};$('dataModeStatus').textContent=HongData.fallback?'· API 보완 켜짐':'· Render 요청 없음'}const initial=location.hash.slice(1);show(pages.includes(initial)?initial:'home',false);setInterval(()=>{if(document.hidden)return;if(state.page==='turnover')loadTurnover();if(state.page==='watchlist')renderWatch();if(state.page==='home'){loadOverview();loadPicks()}if(state.page==='hongpicks')loadPicks();if(state.page==='search'&&state.search)loadDetails(state.search)},HongData.staticMode?300000:90000);setInterval(()=>{if(!document.hidden&&['home','fng'].includes(state.page))loadFng()},1800000);setInterval(()=>{if(!document.hidden&&state.page==='gurus')loadGurus()},21600000);setInterval(()=>{if(!document.hidden&&state.page==='trump')loadTrump()},3600000);




async function loadPicks(){
 if(picksPending)return picksPending;
 picksPending=(async()=>{try{picksData=await api('/api/hongpicks');renderPicks()}catch(error){for(const id of ['picksList','homePicks'])notice($(id),error.message);for(const id of ['picksSource','homePicksSource'])$(id).textContent='추천 데이터 없음 · 다른 메뉴는 계속 사용할 수 있습니다.'}finally{picksPending=null}})();return picksPending;
}
function pickRow(x,index,compact=false){
 const stars='★'.repeat(x.stars)+'☆'.repeat(5-x.stars),week=x.weekly;
 const badges=[`<span class="${x.rsi<=30?'met':''}">일봉 RSI ${number(x.rsi,1)}</span>`,`<span class="${week&&week.distance<=5?'met':''}">${week?'주봉 빗각 '+number(week.distance,1)+'%':'주봉 채널 없음'}</span>`,`<span class="${x.golden?.matched?'met':''}">${x.golden?.matched?'골든크로스 '+x.golden.date:x.golden?'골든크로스 없음':'MA 데이터 없음'}</span>`,`<span class="${x.rally>=10?'met':''}">본장 ${percent(x.rally)}</span>`];
 return `<button class="pick-row ${compact?'compact':''}" data-pick-tv="${escapeHtml(x.tv)}"><span class="pick-rank">${index+1}</span><span class="pick-info"><b>${escapeHtml(x.name)}</b><small>${escapeHtml(x.ticker)} · ${x.market==='kr'?'한국':'미국'} · ${number(x.price)} ${escapeHtml(x.currency||'')}</small><span class="pick-signals">${badges.join('')}</span>${compact?'':`<small>본장 기준 ${escapeHtml(x.sessionDate)}${x.stale?' · 이전 수집 데이터':''}${week?' · '+(week.mode==='high'?'고–고–고':'저–저–저')+' 레벨 '+week.ratio+' · '+number(week.line)+' '+escapeHtml(x.currency||''):''}</small>`}</span><span class="pick-rating"><span class="pick-stars" aria-label="추천 별 ${x.stars}개 / 5개">${stars}</span><small>${number(x.score)} / 100</small>${x.score===0?'<small>신호 없음</small>':''}</span></button>`;
}
function renderPicks(){
 if(!picksData)return;const all=picksData.rows||[],rows=all.filter(x=>picksMarket==='all'||x.market===picksMarket).slice(0,50);
 $('picksTitle').textContent=(picksMarket==='all'?'전체':picksMarket==='us'?'미국':'한국')+' 홍픽종목 TOP50';$('picksCount').textContent=`${rows.length}개 표시 · ${all.length}/${picksData.candidateCount}개 분석`;
 $('picksList').innerHTML=rows.length?rows.map((x,i)=>pickRow(x,i)).join(''):'<div class="empty">분석 가능한 실제 데이터가 없습니다.</div>';
 $('homePicks').innerHTML=all.length?all.slice(0,10).map((x,i)=>pickRow(x,i,true)).join(''):'<div class="empty">분석 가능한 실제 데이터가 없습니다.</div>';
 for(const id of ['picksSource','homePicksSource'])$(id).textContent=source(picksData)+' · 일봉 종가 기준 · 약 30분마다 수집'+(picksData.failures?.length?' · '+picksData.failures.length+'개 종목 일봉 데이터 없음':'');
 document.querySelectorAll('[data-pick-tv]').forEach(b=>b.onclick=()=>openPick(all.find(x=>x.tv===b.dataset.pickTv)));
}
async function openPick(item){
 if(!item)return;try{await ensureCharts();if(!charts.search)charts.search=new HongChart($('searchChart'),$('searchIndicators'));charts.search.options.fib=item.weekly?.mode||'off';charts.search.options.fibFrame='W';charts.search.channelSelection=null;charts.search.interval='W';openStock(item)}catch(error){openStock(item)}
}
document.addEventListener('click',e=>{const button=e.target.closest('[data-pick-market]');if(button){picksMarket=button.dataset.pickMarket;document.querySelectorAll('[data-pick-market]').forEach(b=>b.classList.toggle('sel',b===button));renderPicks()}});
