/* TradingView Lightweight Charts 5.2.1. Indicators calculated from returned OHLCV. */
window.HongIndicators = {
 ma(candles, period) { let sum=0;const rows=[];candles.forEach((c,i)=>{sum+=c.close;if(i>=period)sum-=candles[i-period].close;if(i>=period-1)rows.push({time:c.time,value:sum/period})});return rows; },
 rsi(candles,period=14) {let g=0,l=0;const out=[];for(let i=1;i<candles.length;i++){const d=candles[i].close-candles[i-1].close;if(i<=period){g+=Math.max(d,0);l+=Math.max(-d,0);if(i<period)continue;g/=period;l/=period}else{g=(g*(period-1)+Math.max(d,0))/period;l=(l*(period-1)+Math.max(-d,0))/period}out.push({time:candles[i].time,value:l===0?(g===0?50:100):100-100/(1+g/l)})}return out;},
 ichimoku(candles,interval='D') {
  const times=candles.map(c=>c.time);let d=new Date(times.at(-1)+'T12:00:00Z');for(let i=0;i<26;i++){if(interval==='M')d.setUTCMonth(d.getUTCMonth()+1);else if(interval==='W')d.setUTCDate(d.getUTCDate()+7);else{do{d.setUTCDate(d.getUTCDate()+1)}while([0,6].includes(d.getUTCDay()))}times.push(d.toISOString().slice(0,10))}
  const midpoint=(i,p)=>{if(i<p-1)return null;let hi=-Infinity,lo=Infinity;for(let j=i-p+1;j<=i;j++){hi=Math.max(hi,candles[j].high);lo=Math.min(lo,candles[j].low)}return(hi+lo)/2};const conversion=[],base=[],spanA=[],spanB=[],lag=[];
  candles.forEach((c,i)=>{const t=midpoint(i,9),k=midpoint(i,26),b=midpoint(i,52);if(t!=null)conversion.push({time:c.time,value:t});if(k!=null)base.push({time:c.time,value:k});if(t!=null&&k!=null)spanA.push({time:times[i+26],value:(t+k)/2});if(b!=null)spanB.push({time:times[i+26],value:b});if(i>=26)lag.push({time:times[i-26],value:c.close})});
  return {conversion,base,spanA,spanB,lag};
 }
};
class IchimokuCloud {
 constructor(a,b){this.points=a.map(x=>{const y=b.find(y=>y.time===x.time);return y?{time:x.time,a:x.value,b:y.value}:null}).filter(Boolean);this.coordinates=[];this.view={zOrder:()=> 'bottom',renderer:()=>({draw:target=>target.useMediaCoordinateSpace(({context:ctx})=>{for(let i=1;i<this.coordinates.length;i++){const p=this.coordinates[i-1],q=this.coordinates[i];if(!p||!q)continue;const polygon=(left,right,color)=>{ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(left.x,left.a);ctx.lineTo(right.x,right.a);ctx.lineTo(right.x,right.b);ctx.lineTo(left.x,left.b);ctx.closePath();ctx.fill()};const diff=p.a-p.b,next=q.a-q.b;if(diff*next<0){const f=diff/(diff-next);const cross={x:p.x+(q.x-p.x)*f,a:p.a+(q.a-p.a)*f,b:p.b+(q.b-p.b)*f};polygon(p,cross,diff<0?'rgba(22,215,155,0.3)':'rgba(255,82,109,0.3)');polygon(cross,q,next<0?'rgba(22,215,155,0.3)':'rgba(255,82,109,0.3)')}else polygon(p,q,next<0?'rgba(22,215,155,0.3)':'rgba(255,82,109,0.3)')}})})}; }
 attached({chart,series,requestUpdate}){this.chart=chart;this.series=series;this.requestUpdate=requestUpdate;requestUpdate()}
 updateAllViews(){this.coordinates=this.points.map(p=>{const x=this.chart.timeScale().timeToCoordinate(p.time),a=this.series.priceToCoordinate(p.a),b=this.series.priceToCoordinate(p.b);return x==null||a==null||b==null?null:{x,a,b}})}
 paneViews(){return[this.view]}
}
window.HongChart=class {
 constructor(element,controls){this.element=element;this.controls=controls;this.options={ma:new Set([20]),rsi:false,ichi:false};this.interval='D';this.series=[];this.token=0;this.item=null;}
 destroy(){if(this.chart)this.chart.remove();this.chart=null;this.series=[];this.cloud=null;this.candles=null;this.volume=null;}
 async load(item){this.item=item;const token=++this.token;this.destroy();this.element.innerHTML='<div class="chart-unavailable">실제 가격 데이터를 불러오는 중…</div>';this.renderControls();try{const d=await api('/api/history?symbol='+encodeURIComponent(item.tv)+'&interval='+this.interval);if(token!==this.token)return;this.data=d;this.draw();this.renderControls()}catch(e){if(token!==this.token)return;this.element.innerHTML='<div class="chart-unavailable"><b>차트 데이터 없음</b><p>'+escapeHtml(e.message)+'</p><a href="https://www.tradingview.com/chart/?symbol='+encodeURIComponent(item.tv)+'" target="_blank" rel="noopener noreferrer">TradingView에서 확인 ↗</a></div>';this.renderControls()}}
 draw(){this.destroy();this.element.replaceChildren();const L=LightweightCharts;this.chart=L.createChart(this.element,{autoSize:true,layout:{background:{color:'#0b1927'},textColor:'#8194a7',attributionLogo:true,panes:{separatorColor:'#183247'}},grid:{vertLines:{color:'#132a3c'},horzLines:{color:'#132a3c'}},rightPriceScale:{borderColor:'#183247'},timeScale:{borderColor:'#183247',rightOffset:4},localization:{locale:'ko-KR'},crosshair:{mode:L.CrosshairMode.Normal}});this.candles=this.chart.addSeries(L.CandlestickSeries,{upColor:'#16d79b',downColor:'#ff526d',borderVisible:false,wickUpColor:'#16d79b',wickDownColor:'#ff526d'});this.candles.setData(this.data.candles);this.candles.priceScale().applyOptions({scaleMargins:{top:0.08,bottom:0.2}});this.volume=this.chart.addSeries(L.HistogramSeries,{priceFormat:{type:'volume'},priceScaleId:'volume',lastValueVisible:false,priceLineVisible:false});this.volume.setData(this.data.candles.map(c=>({time:c.time,value:c.volume,color:c.close>=c.open?'#16d79b38':'#ff526d38'})));this.volume.priceScale().applyOptions({scaleMargins:{top:0.82,bottom:0}});this.applyIndicators();const count=this.data.candles.length;this.chart.timeScale().setVisibleLogicalRange({from:Math.max(0,count-120),to:count+5});}
 applyIndicators(){if(!this.chart)return;for(const s of this.series)this.chart.removeSeries(s);this.series=[];if(this.cloud){this.candles.detachPrimitive(this.cloud);this.cloud=null}const L=LightweightCharts;const add=(data,color,pane=0)=>{const s=this.chart.addSeries(L.LineSeries,{color,lineWidth:1,lastValueVisible:false,priceLineVisible:false,crosshairMarkerVisible:false},pane);s.setData(data);this.series.push(s);return s};const colors={20:'#f4c95d',60:'#58adff',120:'#b58eff',200:'#f790ad'};for(const p of this.options.ma)add(HongIndicators.ma(this.data.candles,p),colors[p]);if(this.options.ichi){const d=HongIndicators.ichimoku(this.data.candles,this.interval);add(d.conversion,'#4d9bff');add(d.base,'#ff765d');add(d.spanA,'#16d79b');add(d.spanB,'#ff526d');add(d.lag,'#bb8ae8');this.cloud=new IchimokuCloud(d.spanA,d.spanB);this.candles.attachPrimitive(this.cloud)}if(this.options.rsi){const s=add(HongIndicators.rsi(this.data.candles),'#b58eff',1);s.applyOptions({autoscaleInfoProvider:()=>({priceRange:{minValue:0,maxValue:100}})});for(const value of [30,70])s.createPriceLine({price:value,color:'#71899c',lineWidth:1,lineStyle:2,axisLabelVisible:true,title:''});const panes=this.chart.panes();panes[0].setStretchFactor(4);panes[1].setStretchFactor(1.5)}this.renderControls();}
 renderControls(){if(!this.item)return;const saved=state.watch.some(x=>x.tv===this.item.tv);this.controls.innerHTML='<div class="indicator-buttons"><button data-tool="ma" class="'+(this.options.ma.size?'on':'')+'">이동평균선 '+[...this.options.ma].sort((a,b)=>a-b).join('/')+'</button><button data-tool="rsi" class="'+(this.options.rsi?'on':'')+'">RSI(14) '+(this.options.rsi?'ON':'OFF')+'</button><button data-tool="ichi" class="'+(this.options.ichi?'on':'')+'">일목균형표 '+(this.options.ichi?'ON':'OFF')+'</button><button data-watch="'+escapeHtml(this.item.tv)+'" class="'+(saved?'on':'')+'">'+(saved?'★ 저장됨':'☆ 관심 저장')+'</button></div><div class="filters timeframe">'+['D','W','M'].map((v,i)=>'<button data-interval="'+v+'" class="'+(v===this.interval?'sel':'')+'">'+['일봉','주봉','월봉'][i]+'</button>').join('')+'</div><small class="data-source">'+(this.data?escapeHtml(this.data.source)+' · 마지막 봉 '+this.data.lastBar+' · 수집 '+formatDate(this.data.updated)+(this.data.stale?' · 이전 데이터':''):'일봉 가격 데이터')+(this.data&&[...this.options.ma].some(p=>p>this.data.candles.length)?'<br>선택한 MA 중 봉 수가 부족한 기간은 데이터가 없습니다.':'')+'<br>일목: 9 / 26 / 52 / 26 · 구름 불투명도 30% · <a href="https://www.tradingview.com/" target="_blank" rel="noopener noreferrer">Chart by TradingView Lightweight Charts</a></small>';this.controls.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{const k=b.dataset.tool;if(k==='ma')this.maMenu();else{this.options[k==='ichi'?'ichi':'rsi']=!this.options[k==='ichi'?'ichi':'rsi'];this.applyIndicators()}});this.controls.querySelectorAll('[data-interval]').forEach(b=>b.onclick=()=>{this.interval=b.dataset.interval;this.data=null;this.load(this.item)})}
 maMenu(){const back=document.createElement('div');back.className='modal-back';back.innerHTML='<section class="modal" role="dialog" aria-modal="true" aria-label="이동평균선 선택"><div class="modal-head"><h2>이동평균선</h2><button aria-label="닫기">×</button></div><div class="check-list">'+[20,60,120,200].map(p=>'<label><input type="checkbox" value="'+p+'" '+(this.options.ma.has(p)?'checked':'')+'> MA '+p+'</label>').join('')+'</div><small class="data-source">현재 차트 봉의 종가로 계산합니다.</small></section>';const close=()=>back.remove();back.onclick=e=>{if(e.target===back)close()};back.querySelector('button').onclick=close;back.querySelectorAll('input').forEach(input=>input.onchange=()=>{input.checked?this.options.ma.add(+input.value):this.options.ma.delete(+input.value);this.applyIndicators()});back.onkeydown=e=>{if(e.key==='Escape')close()};document.body.append(back);back.querySelector('input').focus()}
 resize(){if(this.chart)this.chart.resize(this.element.clientWidth,this.element.clientHeight)}
};
